# Generated by Django 4.1.2 on 2022-12-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('tel', models.CharField(blank=True, max_length=64, null=True)),
                ('brand', models.CharField(blank=True, max_length=32, null=True)),
                ('model', models.CharField(blank=True, max_length=64, null=True)),
                ('reason', models.CharField(blank=True, max_length=64, null=True)),
                ('solution', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.CharField(blank=True, max_length=8, null=True)),
                ('fin_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
