# Generated by Django 4.1.2 on 2022-12-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_company_location_alter_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
