# Generated by Django 4.1.2 on 2022-12-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='cabel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musteri',
            name='drzac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musteri',
            name='foot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musteri',
            name='module',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musteri',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
