# Generated by Django 4.1.2 on 2022-12-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_musteri_cabel_musteri_drzac_musteri_foot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='customer/static/customer/logo'),
        ),
    ]
