# Generated by Django 4.1.2 on 2022-12-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/customer/logo'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
